# Generated by Django 3.2 on 2022-08-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_userlibrary_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlibrary",
            name="is_library",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="Library",
            ),
        ),
        migrations.AddField(
            model_name="userlibrary",
            name="name",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userlibrary",
            name="password",
            field=models.CharField(max_length=8),
        ),
    ]
