# Generated by Django 3.2 on 2022-08-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20220810_2002"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlibrary",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
