# Generated by Django 3.2 on 2022-08-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_copy", "0002_alter_bookcopy_userbook"),
        ("shelf", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shelf",
            old_name="number",
            new_name="category",
        ),
        migrations.AddField(
            model_name="shelf",
            name="section",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ShelfBookCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("sub_section", models.CharField(max_length=10)),
                (
                    "book_copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_copy.bookcopy",
                    ),
                ),
                (
                    "shelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shelf.shelf"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
