# Generated by Django 3.2 on 2022-08-11 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_copy', '0002_alter_bookcopy_userbook'),
        ('shelf', '0002_auto_20220810_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelfbookcopy',
            name='book_copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_copy.bookcopy', unique=True),
        ),
    ]
