# Generated by Django 3.2 on 2022-08-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="shelf",
        ),
    ]
